### ISSUE TITLE
Enhancement for checking if a username is already taken upon sign up

### ISSUE THREAD

**Issue by AhmedSafi97** [CA-G12/Reddit-App-Fadi#26]
https://github.com/CA-G12/Reddit-App-Fadi/blob/fd0c3b43f7bddef1704983d872b8b7db129f09e6/src/controllers/auth.js#L16-L20

It is not good to select all users from the database then loop through them to check if the username already exist or not, it is better to leave this job for your query. In other words: 
```sql
SELECT USERNAME FROM USERS WHERE USERNAME = the username sent in the request body
```
Then in your code you can do a simple check to see if the query returned a user with that username or not.

**Comment by fadezak100** [comment]
Done. Thanks!
